{{- if not (empty .Values.influxURL) }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "kapacitor.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    app: {{ template "kapacitor.fullname" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "kapacitor.fullname" . }}
      annotations:
        # Include a hash of the config in the pod template
        # This means that if the config changes, the deployment will be rolled
        checksum/config: {{ include (print .Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: KAPACITOR_HOSTNAME
          value: {{ template "kapacitor.fullname" . }}.{{ .Release.Namespace }}
        - name: KAPACITOR_INFLUXDB_0_URLS_0
          value: {{ .Values.influxURL }}
        {{- range $key, $val := .Values.envVars }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end }}

        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: 9092
        volumeMounts:
        - name: data
          mountPath: /var/lib/kapacitor
        - name: config
          mountPath: /etc/kapacitor/
      {{- if .Values.schedulerName }}
      schedulerName: "{{ .Values.schedulerName }}"
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "kapacitor.fullname" . }}
      - name: data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "kapacitor.fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end }}
{{- end }}
